model_name: "Qwen/Qwen2.5-7B"

api_server:
  api_address: "127.0.0.1:8000"

controller:
  route_policy: "round_robin"

llm_servers:
  - kind: "all"
    address: "127.0.0.1:7000"
    engine:
      host_kv_cache_size: 40  # GiB
      disk_kv_cache_size: 120 # GiB
